-- INIT.SQL: CREATE SCHEMA AND SEED DATA FOR LOCAL DEV
-- TABLES: USERS, WALLETS, CATEGORIES, BUDGETS, TRANSACTIONS

-- USERS
CREATE TABLE IF NOT EXISTS USERS (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(30) NOT NULL UNIQUE,
  PHONE VARCHAR(10), -- THÊM PHONE ĐỂ GỬI SMS CẢNH BÁO NGÂN SÁCH
  ADDRESS VARCHAR(255),
  PASSWORD_HASH TEXT,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- WALLETS
CREATE TABLE IF NOT EXISTS WALLETS (
  ID SERIAL PRIMARY KEY,
  USER_ID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE,
  NAME VARCHAR(50) NOT NULL,
  TYPE VARCHAR(10) DEFAULT 'cash', -- VÍ DỤ: 'cash', 'bank', 'credit', 'ewallet'
  BALANCE NUMERIC(18,2) DEFAULT 0,
  CURRENCY VARCHAR(10) DEFAULT 'VND',
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CATEGORIES
CREATE TABLE IF NOT EXISTS CATEGORIES (
  ID SERIAL PRIMARY KEY,
  USER_ID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE, -- NULL NẾU LÀ DANH MỤC MẶC ĐỊNH CHUNG
  NAME VARCHAR(100) NOT NULL,
  ICON VARCHAR(25), -- LƯU EMOJI HOẶC TÊN CLASS ICON (VD: '🍔', 'FaUtensils')
  COLOR VARCHAR(15)
);

-- BUDGETS
CREATE TABLE IF NOT EXISTS BUDGETS (
  ID SERIAL PRIMARY KEY,
  USER_ID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE,
  CATEGORY_ID INTEGER REFERENCES CATEGORIES(ID) ON DELETE SET NULL,
  AMOUNT NUMERIC(18,2) NOT NULL DEFAULT 0,
  PERIOD VARCHAR(32) DEFAULT 'monthly',
  IS_ALERT_ENABLED BOOLEAN DEFAULT FALSE -- TRẠNG THÁI BẬT/TẮT SMS/EMAIL CẢNH BÁO
);

-- TRANSACTIONS
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
  ID SERIAL PRIMARY KEY,
  WALLET_ID INTEGER REFERENCES WALLETS(ID) ON DELETE CASCADE,
  USER_ID INTEGER REFERENCES USERS(ID) ON DELETE CASCADE,
  CATEGORY_ID INTEGER REFERENCES CATEGORIES(ID) ON DELETE SET NULL,
  AMOUNT NUMERIC(18,2) NOT NULL,
  TYPE VARCHAR(16) NOT NULL CHECK (TYPE IN ('expense','income','transfer')),
  DESCRIPTION TEXT,
  LOCATION VARCHAR(255), -- HỖ TRỢ AI NHẬN DIỆN ĐỊA ĐIỂM CHI TIÊU
  IMAGE_URL TEXT, -- LƯU ĐƯỜNG DẪN ẢNH HÓA ĐƠN ĐÍNH KÈM
  TRANSACTION_DATE DATE NOT NULL DEFAULT CURRENT_DATE, -- NGÀY THỰC TẾ XẢY RA GIAO DỊCH
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SAMPLE SEED DATA
INSERT INTO USERS (NAME, EMAIL, PHONE, ADDRESS) VALUES ('Demo User', 'demo@local', '0901234567', 'Gia Lai') ON CONFLICT (EMAIL) DO NOTHING;

DO $$
DECLARE U_ID INTEGER;
BEGIN
  SELECT ID INTO U_ID FROM USERS WHERE EMAIL = 'demo@local';
  IF U_ID IS NULL THEN RETURN; END IF;

  -- CATEGORIES (THÊM ICON)
  INSERT INTO CATEGORIES (NAME, ICON, COLOR) VALUES ('Ăn uống', '🍔', '#F97316') ON CONFLICT DO NOTHING;
  INSERT INTO CATEGORIES (NAME, ICON, COLOR) VALUES ('Di chuyển', '🚗', '#06B6D4') ON CONFLICT DO NOTHING;
  INSERT INTO CATEGORIES (NAME, ICON, COLOR) VALUES ('Giải trí', '🎬', '#E11D48') ON CONFLICT DO NOTHING;

  -- WALLETS (THÊM TYPE ĐỂ PHÂN LOẠI THẺ ATM)
  INSERT INTO WALLETS (USER_ID, NAME, TYPE, BALANCE) VALUES (U_ID, 'Tiền mặt', 'cash', 15000000) ON CONFLICT DO NOTHING;
  INSERT INTO WALLETS (USER_ID, NAME, TYPE, BALANCE) VALUES (U_ID, 'Vietcombank', 'bank', 32000000) ON CONFLICT DO NOTHING;

  -- BUDGETS (BẬT CẢNH BÁO)
  INSERT INTO BUDGETS (USER_ID, CATEGORY_ID, AMOUNT, PERIOD, IS_ALERT_ENABLED)
    SELECT U_ID, C.ID, 5000000, 'monthly', TRUE FROM CATEGORIES C WHERE C.NAME = 'Ăn uống' LIMIT 1;

  -- TRANSACTIONS (THÊM LOCATION ĐỂ AI RA LỜI KHUYÊN CHUẨN XÁC)
  INSERT INTO TRANSACTIONS (WALLET_ID, USER_ID, CATEGORY_ID, AMOUNT, TYPE, DESCRIPTION, LOCATION)
    SELECT W.ID, U_ID, C.ID, 250000, 'expense', 'Surf Bar', 'Quy Nhơn, Gia Lai' 
    FROM WALLETS W, CATEGORIES C WHERE W.USER_ID = U_ID AND C.NAME = 'Ăn uống' LIMIT 1;
END$$;