-- ====================================================================
-- PART 1: DATA DEFINITION LANGUAGE (DDL) - DATABASE STRUCTURE
-- ====================================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS USERS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    PHONE VARCHAR(10),
    PASSWORD_HASH TEXT,
    ADDRESS VARCHAR(100),
    AVATAR_URL TEXT,
    LANGUAGE VARCHAR(10) DEFAULT 'vi',
    DATE_FORMAT VARCHAR(20) DEFAULT 'DD/MM/YYYY',
    SMS_ALERT BOOLEAN DEFAULT FALSE,
    WEEKLY_REPORT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS CATEGORIES (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE, -- NULL indicates system-wide default categories
    NAME VARCHAR(100) NOT NULL UNIQUE,
    ICON VARCHAR(25),                                      -- Stores Emoji or Icon Class names (e.g., '🍔')
    COLOR VARCHAR(15)
);

-- 3. WALLETS TABLE
CREATE TABLE IF NOT EXISTS WALLETS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE,
    NAME VARCHAR(50) NOT NULL,
    TYPE VARCHAR(10) DEFAULT 'cash',                       -- Supported: 'cash', 'bank', 'credit', 'ewallet'
    ACCOUNT_NUMBER VARCHAR(20),
    DESCRIPTION VARCHAR(100),
    BALANCE NUMERIC(18,2) DEFAULT 0,
    CURRENCY VARCHAR(10) DEFAULT 'VND',
    COLOR VARCHAR(100),                                    -- Stores Tailwind CSS Gradient strings
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. BUDGETS TABLE
CREATE TABLE IF NOT EXISTS BUDGETS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE,
    CATEGORY_ID BIGINT REFERENCES CATEGORIES(ID) ON DELETE SET NULL,
    AMOUNT NUMERIC(18,2) NOT NULL DEFAULT 0,
    PERIOD VARCHAR(32) DEFAULT 'monthly',
    IS_ALERT_ENABLED BOOLEAN DEFAULT FALSE,
    START_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    END_DATE DATE NOT NULL DEFAULT CURRENT_DATE
);

-- 5. TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE,
    WALLET_ID BIGINT REFERENCES WALLETS(ID) ON DELETE CASCADE,
    CATEGORY_ID BIGINT REFERENCES CATEGORIES(ID) ON DELETE SET NULL,
    AMOUNT NUMERIC(18,2) NOT NULL,
    TYPE VARCHAR(16) NOT NULL CHECK (TYPE IN ('expense','income','transfer')),
    DESCRIPTION TEXT,
    LOCATION VARCHAR(255),                                 -- Used for AI-driven location insights
    IMAGE_URL TEXT,                                        -- Stores receipt OCR image references
    TRANSACTION_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. CHAT_HISTORY TABLE
CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE,
    ROLE VARCHAR(10) NOT NULL CHECK (ROLE IN ('user', 'ai')),
    CONTENT TEXT NOT NULL,
    IMAGE_URL TEXT,                                        -- Supports Base64 strings or storage URLs for OCR
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    TITLE VARCHAR(255) NOT NULL,
    MESSAGE VARCHAR(500) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    IS_READ BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ====================================================================
-- PART 2: DATA MANIPULATION LANGUAGE (DML) - SEED DATA FOR DEV ENVIRONMENT
-- ====================================================================

-- 1. Insert Base User Profile
INSERT INTO USERS (NAME, EMAIL, PHONE, PASSWORD_HASH, ADDRESS, LANGUAGE, SMS_ALERT, WEEKLY_REPORT) 
VALUES ('Hồ Thanh Nhàn', 'nhanht1101@gmail.com', '0372592762', '123456', 'Quy Nhon, Binh Dinh', 'vi', FALSE, FALSE) 
ON CONFLICT (EMAIL) DO NOTHING;

-- 2. Seed Related Relational Data
DO $$
DECLARE 
    TARGET_USER_ID BIGINT;
    CAT_FOOD_ID BIGINT;
    W_VCB_ID BIGINT;
BEGIN
    -- Retrieve target user reference ID
    SELECT ID INTO TARGET_USER_ID FROM USERS WHERE EMAIL = 'nhanht1101@gmail.com';
    IF TARGET_USER_ID IS NULL THEN RETURN; END IF;

    -- Seed Custom Categories with associated UI Metadata
    INSERT INTO CATEGORIES (NAME, ICON, COLOR) VALUES ('Ăn uống', '🍔', '#F97316') ON CONFLICT (NAME) DO NOTHING;
    INSERT INTO CATEGORIES (NAME, ICON, COLOR) VALUES ('Di chuyển', '🚗', '#06B6D4') ON CONFLICT (NAME) DO NOTHING;
    INSERT INTO CATEGORIES (NAME, ICON, COLOR) VALUES ('Giải trí', '🎬', '#E11D48') ON CONFLICT (NAME) DO NOTHING;
    INSERT INTO CATEGORIES (NAME, ICON, COLOR) VALUES ('Quỹ dự phòng tự do', '🏦', '#8B5CF6') ON CONFLICT (NAME) DO NOTHING;

    SELECT ID INTO CAT_FOOD_ID FROM CATEGORIES WHERE NAME = 'Ăn uống' LIMIT 1;

    -- Seed 4 distinctive operational wallets with matched Tailwind Gradient setups
    IF NOT EXISTS (SELECT 1 FROM WALLETS WHERE USER_ID = TARGET_USER_ID AND NAME = 'Vietcombank') THEN
        INSERT INTO WALLETS (USER_ID, NAME, TYPE, ACCOUNT_NUMBER, DESCRIPTION, BALANCE, COLOR)
        VALUES (TARGET_USER_ID, 'Vietcombank', 'bank', '5231', 'Salary Account', 15500000.00, 'from-purple-600 to-pink-500');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM WALLETS WHERE USER_ID = TARGET_USER_ID AND NAME = 'Tiền mặt') THEN
        INSERT INTO WALLETS (USER_ID, NAME, TYPE, ACCOUNT_NUMBER, DESCRIPTION, BALANCE, COLOR)
        VALUES (TARGET_USER_ID, 'Tiền mặt', 'cash', NULL, 'Physical Cash', 650000.00, 'from-orange-500 to-amber-500');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM WALLETS WHERE USER_ID = TARGET_USER_ID AND NAME = 'MoMo') THEN
        INSERT INTO WALLETS (USER_ID, NAME, TYPE, ACCOUNT_NUMBER, DESCRIPTION, BALANCE, COLOR)
        VALUES (TARGET_USER_ID, 'MoMo', 'ewallet', '0001', 'Pocket Money', 1250000.00, 'from-sky-400 to-blue-600');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM WALLETS WHERE USER_ID = TARGET_USER_ID AND NAME = 'VIB Credit') THEN
        INSERT INTO WALLETS (USER_ID, NAME, TYPE, ACCOUNT_NUMBER, DESCRIPTION, BALANCE, COLOR)
        VALUES (TARGET_USER_ID, 'VIB Credit', 'credit', '9876', 'Shopping Card', 7800000.00, 'from-gray-800 to-slate-900');
    END IF;

    SELECT ID INTO W_VCB_ID FROM WALLETS WHERE USER_ID = TARGET_USER_ID AND NAME = 'Vietcombank' LIMIT 1;

    -- Seed standard monthly tracking budget limits
    IF NOT EXISTS (SELECT 1 FROM BUDGETS WHERE USER_ID = TARGET_USER_ID AND CATEGORY_ID = CAT_FOOD_ID) THEN
        INSERT INTO BUDGETS (USER_ID, CATEGORY_ID, AMOUNT, PERIOD, IS_ALERT_ENABLED, START_DATE, END_DATE)
        VALUES (TARGET_USER_ID, CAT_FOOD_ID, 5000000.00, 'monthly', TRUE, CURRENT_DATE, CURRENT_DATE + INTERVAL '1 month');
    END IF;

    -- Seed an initial transaction item
    IF NOT EXISTS (SELECT 1 FROM TRANSACTIONS WHERE USER_ID = TARGET_USER_ID AND DESCRIPTION = 'Surf Bar') THEN
        INSERT INTO TRANSACTIONS (WALLET_ID, USER_ID, CATEGORY_ID, AMOUNT, TYPE, DESCRIPTION, LOCATION, TRANSACTION_DATE)
        VALUES (W_VCB_ID, TARGET_USER_ID, CAT_FOOD_ID, 250000.00, 'expense', 'Surf Bar', 'Quy Nhon, Binh Dinh', CURRENT_DATE);
    END IF;

END$$;
